import QueryProvider from "@/contexts/query-provider";
import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import SessionProvider from "@/contexts/session-provider";

// const inter = Inter({ subsets: ['latin'] })
const bricolageGrotesk = Bricolage_Grotesque({
  subsets: ["latin"],
  weight: "700",
  display: "swap",
  adjustFontFallback: false,
});

export const metadata: Metadata = {
  title: "StudyJom",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`scroll-smooth scrollbar-hide ${bricolageGrotesk.className}`}
      >
        <QueryProvider>
          <SessionProvider>
            {children}
            <Toaster reverseOrder={false} />
          </SessionProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
